### ISSUE TITLE
[Bug]: Schematron validation reports an error for set-parameter check

### ISSUE THREAD

**Issue by volpet2014** [vitg-gsa-automation/earlyadopters#11]
### Portal version

2.2.0

### What happened?

The below representation of an implemented-requirement continuously fails the implemented-requirement set-parameter rule, “In the corresponding baseline-resolved-profile catalog, all param elements, that do not have child value elements, have an @id value that also occurs in the matching implemented-requirement set-parameter element @id in the SSP.”

        <implemented-requirement uuid="b49b77de-9481-474e-988b-a0c8526d0296" control-id="ac-4">
          <prop name="planned-completion-date" uuid="f584f6f9-5456-49fd-86a3-5be926d1881d" ns="https://fedramp.gov/ns/oscal" value="2023-12-31Z" />
          <prop name="implementation-status" uuid="650363d3-291d-4adb-a4f4-cac8799db504" ns="https://fedramp.gov/ns/oscal" value="implemented" />
          <prop name="control-origination" uuid="dd25e221-af17-430f-95ea-362df7550dd4" ns="https://fedramp.gov/ns/oscal" value="sp-system" />
          <responsible-role role-id="system-owner">
            <party-uuid>03ee9bef-54ba-4cff-8e86-5f76326d0f09</party-uuid>
          </responsible-role>
          <statement statement-id="ac-4_smt" uuid="c68254cd-2360-4c64-bf06-968bb78638f3">
            <by-component component-uuid="f3b0ed36-b149-4844-8378-6e2c5ae2f37e" uuid="fb807a33-479c-4a7c-bf96-5fe5d1ecfce7">
              <description>
                <p>The information system enforces approved authorizations for controlling the flow of information within the system and between interconnected systems based on Organization information flow control policy document.</p>
              </description>
              <set-parameter param-id="ac-4_prm_1">
                <value>Organization information flow control policy document</value>
              </set-parameter>
              <implementation-status state="implemented" />
            </by-component>
          </statement>

### Reproduction

Attached file fails this validation check with an error:  “In the corresponding baseline-resolved-profile catalog, all param elements, that do not have child value elements, have an @id value that also occurs in the matching implemented-requirement set-parameter element @id in the SSP.” when running through FedRAMP Validations.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vitg-gsa-automation/earlyadopters/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vitg-gsa-automation/earlyadopters/issues) for duplicate problems

**Comment by volpet2014** [comment]
@volpet2014 - Issue is that set-parameter can appear at multiple levels within the implemented-requirement assembly.  Schematron is only checking at the highest level.   This will be fixed in our next update to the Schematron rulesets.  This can be triaged currently by moving the set-parameter up from under statement/by-component to under implemented requirement.  See sample below for correction.
=============================================
        <implemented-requirement uuid="b49b77de-9481-474e-988b-a0c8526d0296" control-id="ac-4">
          <prop name="planned-completion-date" uuid="f584f6f9-5456-49fd-86a3-5be926d1881d" ns="https://fedramp.gov/ns/oscal" value="2023-12-31Z" />
          <prop name="implementation-status" uuid="650363d3-291d-4adb-a4f4-cac8799db504" ns="https://fedramp.gov/ns/oscal" value="implemented" />
          <prop name="control-origination" uuid="dd25e221-af17-430f-95ea-362df7550dd4" ns="https://fedramp.gov/ns/oscal" value="sp-system" />
          **<set-parameter param-id="ac-4_prm_1">
            <value>organization-defined information flow control policies</value>
          </set-parameter>**
          <responsible-role role-id="system-owner">
            <party-uuid>03ee9bef-54ba-4cff-8e86-5f76326d0f09</party-uuid>
          </responsible-role>
          <statement statement-id="ac-4_smt" uuid="c68254cd-2360-4c64-bf06-968bb78638f3">
            <by-component component-uuid="f3b0ed36-b149-4844-8378-6e2c5ae2f37e" uuid="fb807a33-479c-4a7c-bf96-5fe5d1ecfce7">
              <description>
                <p>The information system enforces approved authorizations for controlling the flow of information within the system and between interconnected systems based on Organization information flow control policy document.</p>
              </description>
              <implementation-status state="implemented" />
            </by-component>
          </statement>
        </implemented-requirement>
================================================================

**Comment by dimitri-zhurkin-vitg** [comment]
The error was legitimate. It was caused by duplicate parameters in the SSP and the moderate baseline resolved profile catalog.
