### ISSUE TITLE
[Bug]: Rule 55b. One or more responsible parties must be defined for each role

### ISSUE THREAD

**Issue by vmangat** [vitg-gsa-automation/earlyadopters#12]
### Portal version

2.2.0

### What happened?

This rule requires all roles defined in the metadata to have at least one ResponsibleParty associated with it. 
This contradicts the OSCAL requirements that all roles being used by ResponsibleParty or ResponsibleRole or UserTypes must be listed in the Metadata so they can be referenced. Roles used in ResponbsibleRoles and UserTypes will not have associated ResponsibleParty.

### Reproduction

We have provided a file Pinnacle_Learning_Management_System_-_System_Security_Plan_With_Errors.json which demonstrates the the dataset and the errors.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vitg-gsa-automation/earlyadopters/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vitg-gsa-automation/earlyadopters/issues) for duplicate problems

**Comment by volpet2014** [comment]
The current file dated 9/20 on the portal looks to have this issue resolved.  We were unable to re-create the issue.  More insight is needed.

**Comment by vmangat** [comment]
We emailed a file on 9/15 it demonstrates this issue.
