### ISSUE TITLE
[Bug]: Rule 48.a  A component must have an allowed type.

### ISSUE THREAD

**Issue by vmangat** [vitg-gsa-automation/earlyadopters#13]
### Portal version

2.2.0

### What happened?

Component Type for leveraged system is required to be "system" per OSCAL.

FedRAMP 1.2.2 guidebook requires the Component Type for leveraged system to be "leveraged-system" and the Schematron Rev4 validation rules have neither "leveraged-system" nor "system" in the valid values so this rule fails consistently.

### Reproduction

we have included a file in the portal Pinnacle_Learning_Management_System_-_System_Security_Plan_With_Errors.json that demonstrates this scenario

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vitg-gsa-automation/earlyadopters/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vitg-gsa-automation/earlyadopters/issues) for duplicate problems

**Comment by volpet2014** [comment]
Do not see file attached per note above  (Pinnacle_Learning_Management_System_-_System_Security_Plan_With_Errors.json).
Please provide.

**Comment by volpet2014** [comment]
We are engaging the PMO and Rene on Guide to ascertain why this was different from NIST "system".  Fix pending once that has been resolved.

**Comment by volpet2014** [comment]
The automation team has added "leveraged-system" to the fedramp-values resource file for Rev 4 and Rev 5  See associated PR. 
This will be implemented for OEAW portal version 2.3.
