### ISSUE TITLE
[Bug]: Rule 41. Every Asset Identifier must be unique

### ISSUE THREAD

**Issue by vmangat** [vitg-gsa-automation/earlyadopters#15]
### Portal version

2.2.0

### What happened?

FedRAMP requires an AssetId to be deifined in the Component assembly

OSCAL requires an AssetId to be provided in InventoryItem/ImplementedComponents/assetID.

We used the component/asset-id to satisfy inventory-item/impelemented-components/asset=id.

### Reproduction

We have provided a sample file in the portal Pinnacle_Learning_Management_System_-_System_Security_Plan_With_Errors.json which demonstrates the situation.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vitg-gsa-automation/earlyadopters/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vitg-gsa-automation/earlyadopters/issues) for duplicate problems

**Comment by volpet2014** [comment]
No file attached.  Can you provide?

**Comment by volpet2014** [comment]
After reviewing the submitted sample, we find there are duplicates that exit for asset-id in the document. Each asset-id whether associated with the inventory item or component must be unique.  (See below example)
```xml
<components>
    <uuid>99da94c8-f27d-4b53-b0af-93bfabce5436</uuid>
    <description>Software Component of the Proxy Server for the System.</description>
    <type>software</type>
    <title>Proxy Server</title>
    <status>
        <state>operational</state>
    </status>
    <props>
        <name>asset-id</name>
        <value>5</value>    ///  first occurence of asset-id 5
    </props>
    <props>
        <name>virtual</name>
        <value>yes</value>
    </props>
    <props>
        <name>function</name>
        <value>Proxy Server for the System</value>
    </props>
    <props>
        <name>asset-type</name>
        <value>router</value>
    </props>
</components>
<inventory-items>
    <uuid>40d5db13-5d17-423a-8f85-4087f1c294e6</uuid>
    <description>Transport Proxy Server</description>
    <props>...</props>
    <props>
        <name>asset-id</name>
        <value>15</value>
    </props>
    <props>
        <name>scan-type</name>
        <ns>https://fedramp.gov/ns/oscal</ns>
        <value>web</value>
    </props>
    <implemented-components>
        <component-uuid>99da94c8-f27d-4b53-b0af-93bfabce5436</component-uuid>
        <props>
            <name>asset-id</name>
            <ns>http://csrc.nist.gov/ns/oscal</ns>
            <value>5</value>       /// second occurence of asset-id 5
        </props>
    </implemented-components>
</inventory-items>

**Comment by vmangat** [comment]
We had to duplicate the asset-id to satisfy both NIST and FedRAMP requirements.  If we don't duplicate the asset-id we will fail the NIST requirements.  So one party needs to change

**Comment by vmangat** [comment]
![image](https://github.com/vitg-gsa-automation/earlyadopters/assets/98432030/2c104a7e-218f-444e-a349-77e506c704a3)


The prop is in SSP/system-implementation/inventory-item/implemented-component/prop [@name=asset-id]

**Comment by volpet2014** [comment]
I see what your saying.   However, It has to be "unique"  across the entire document based on my understanding of the schematron rule.  The SSP sample code we have repeats the asset-id at the inventory and implemented-component level.   Are you saying NIST flags this if you make each one unique?
