### ISSUE TITLE
[Bug]: Rule 82b and c. import-profile directive with a URL does not resolve

### ISSUE THREAD

**Issue by vmangat** [vitg-gsa-automation/earlyadopters#16]
### Portal version

2.2.0

### What happened?

In an SSP, the import-profile is pointing to the FedRAMP resolved catalog URL

The import-profile href is not resolving successfully.

The Schematron code for Rule 82c is checking for a resolved oscal:catalog only and not for a oscal:profile also, it should be checking for both.

### Reproduction

The file we provided in the portal with errors demonstrates these errors

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vitg-gsa-automation/earlyadopters/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vitg-gsa-automation/earlyadopters/issues) for duplicate problems

**Comment by volpet2014** [comment]
Per Guide to OSCAL-based FedRAMP System Security Plans (Section 3.2.1) the import-profile must reference a resolved-profile-catalog document in FedRAMP.   We recognize that the language in section 3.5 is contradictatory and will be addressed in a subsequent document update.

**Comment by vmangat** [comment]
1. So is the guidance that the import directive should reference a **resolved profile catalog ONLY**, or that it can reference a **Profile OR a resolved profile catalog**.
2. Is the Schematron on the portal updated to be able to successfully resolve.

**Comment by volpet2014** [comment]
According to section 3.2.1 it is resolved-profile-catalog.   However section 3.5 contradicts that guidance.  Working with Rene to fix the Guides.   I have never seen an SSP with just the profile imported.  The response points etc are defined in the resolved-profile-catalog and Schematron utilizes that in verifying certain elements.

**Comment by volpet2014** [comment]
<img width="542" alt="image" src="https://github.com/vitg-gsa-automation/earlyadopters/assets/59895576/e8ce7f4a-229d-49fc-b251-11050748aab8">


According to NIST schema on their site this prop is optional and they don't specifically check the identifier value 'asset-id'.  Can you provide more information regarding which NIST constraint fails?   Maybe we are looking at the wrong identifier.

**Comment by vmangat** [comment]
The OSCAL field is import-profile.   It expects the link to be a Profile.   The response points are in the FedRAMP Profile...they carry onto the resolved profile catalog which is Catalog....but the SSP should not import a catalog.

**Comment by volpet2014** [comment]
Valinder - lets do a quick meeting on this.   I put the asset-id response on this ticket by mistake.  Too much going on today.  Sorry man.

**Comment by vitggsa** [comment]
Final determination based on schematron validation requirements is that the import-profile should specify the resolve-profile-catalog and not the profile itself.  Schematron will raise errors if only a profile is specified.  This is a requirement for the fedramp use case of OSCAL.
