### ISSUE TITLE
[Bug]: Fatal errors for associated documents in POAM Import

### ISSUE THREAD

**Issue by Telos-sa** [vitg-gsa-automation/earlyadopters#18]
### Portal version

2.21

### What happened?

Have two fatal errors that should be warning or informational, about being able to reference available documentation.
Until the package submission process is sorted, this will be an issue.  Recommend downgrading to warning.  Provided the POAM export, and the svrl report.  
[evidence.zip](https://github.com/vitg-gsa-automation/earlyadopters/files/12551643/evidence.zip)

### Reproduction

re-import the provided POAM model.  

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vitg-gsa-automation/earlyadopters/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vitg-gsa-automation/earlyadopters/issues) for duplicate problems

**Comment by volpet2014** [comment]
Resolved in portal validations release 2.3.  Will subsequently do a PR on the fedramp-automation repo to relax the assertion to a "warning" level.
