### ISSUE TITLE
[Bug]: SAP Conversion Failure (Status code 400)

### ISSUE THREAD

**Issue by Telos-sa** [vitg-gsa-automation/earlyadopters#19]
### Portal version

2.2.1

### What happened?

Expected that the SAP would convert, and we should be able to review schematron constraints.  instead, we have this error.  
![image](https://github.com/vitg-gsa-automation/earlyadopters/assets/127163717/d9d3be62-aebb-4155-917a-17367e93f74c)
[FedRAMP---Major-System-Boundary_SAP.json.zip](https://github.com/vitg-gsa-automation/earlyadopters/files/12551816/FedRAMP---Major-System-Boundary_SAP.json.zip)

### Reproduction

Provided the SAP that caused the error.  

Attempted to determine if it was a markup rule issue, but did only the title is a markup line, and there were no / to escape.  

To reproduce, upload the same sap to validate.  

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vitg-gsa-automation/earlyadopters/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vitg-gsa-automation/earlyadopters/issues) for duplicate problems

**Comment by ThomAPenn** [comment]
![FEDRAMPY](https://github.com/vitg-gsa-automation/earlyadopters/assets/107951509/9271ec94-ce4f-4fed-bf41-714d4e34410d)
I ran the oscal-cli tool and it is giving the error that it can't find the root element.  When you are converting the file from Json to XML it is good to have a clear root element or the document will throw errors.  I will edit the json and see if I can't get a clear root element.

**Comment by ThomAPenn** [comment]
THanks for your post... After further review  we have found the problem thanks to your post

**Comment by ThomAPenn** [comment]
This has been updated and fixed and will be ready for the next release.

**Comment by ThomAPenn** [comment]
The option from oscal-cli has changed from sap to ap.  This has been changed and will be ready for next release.
