### ISSUE TITLE
File Upload and Validate Functionality Does Not Support File Names with Spaces

### ISSUE THREAD

**Issue by anolan23** [vitg-gsa-automation/earlyadopters#2]
### Portal version

v2.0.0

### What happened?

In the current system, file names with spaces are not supported during both the file upload and validate processes. If a user attempts to upload or validate a file with spaces in the name, the system prompts an alert message asking the user to replace spaces in the file names with underscores "_". This disrupts the workflow of users who attempt to upload or validate files containing spaces in their names.

### Reproduction

1. Navigate to either the file upload section or the validation section of the portal.
2. Attempt to upload or validate a file that includes spaces in the file name.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](link-to-code-of-conduct)
- [X] I checked the [current issues](https://github.com/{owner}/{repo}/issues) for duplicate problems

**Comment by anolan23** [comment]
The reason this was an issue is because the Validations API cant process files that have filenames with spaces for FedRAMP validations. 

The current fix for this is to have the client side use the `file_name` that is returned (after uploading to container) for subsequent calls to validate/fetch results. 

@ThomAPenn However in the future, the Validations API should handle all of this itself. Other clients that use this API wouldn't how to handle spaces in filenames

**Comment by volpet2014** [comment]
Resolved in version 2.2.0 release of Portal and REST API services.
