### ISSUE TITLE
[Bug]: Swagger sites Failing to load

### ISSUE THREAD

**Issue by Telos-sa** [vitg-gsa-automation/earlyadopters#21]
### Portal version

2.2.1

### What happened?

When the site is entered into the browser, user should be able to view the swagger index for multiple sites.  Instead of errors shown below.

8082:
![image](https://github.com/vitg-gsa-automation/earlyadopters/assets/127163717/bf0fb2e9-7929-49bf-8538-65f74a5b234d)
8084:
![image](https://github.com/vitg-gsa-automation/earlyadopters/assets/127163717/7a51ae46-868a-4fea-a398-119f064e4c3f)
8086:
![image](https://github.com/vitg-gsa-automation/earlyadopters/assets/127163717/0ce01bb3-f194-475c-8e64-6b58f9ca7c94)
8089:
![image](https://github.com/vitg-gsa-automation/earlyadopters/assets/127163717/f838175c-5cea-4818-ab71-4186263157a4)

Sites with an available index are based on the documentation provided
[WebAPI Documentation-1.pdf](https://github.com/vitg-gsa-automation/earlyadopters/files/12561740/WebAPI.Documentation-1.pdf)

### Reproduction

These swagger sites fail to load:
https://appint.volpegroup.com:8082/swagger/index.html 
https://appint.volpegroup.com:8084/swagger/index.html
https://appint.volpegroup.com:8086/swagger/index.html
https://appint.volpegroup.com:8089/swagger/index.html

confirmed these sites do load:
https://appint.volpegroup.com:8081/swagger/index.html 
https://appint.volpegroup.com:8080/swagger/index.html
https://appint.volpegroup.com:8083/swagger/index.html
https://appint.volpegroup.com:8085/swagger/index.html
https://appint.volpegroup.com:8087/swagger/index.html

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vitg-gsa-automation/earlyadopters/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vitg-gsa-automation/earlyadopters/issues) for duplicate problems

**Comment by volpet2014** [comment]
Both file services and Integration services on appdev environments.   See Word document https://github.com/vitg-gsa-automation/earlyadopters/blob/main/presentations/materials/WebAPI%20Documentation.pdf  for specific details.  It was documented in there that they are not running in appint environment due to current location of File Repository.
