### ISSUE TITLE
Loading Indicator Hangs on Accounts Page

### ISSUE THREAD

**Issue by anolan23** [vitg-gsa-automation/earlyadopters#3]
### Portal version

v2.1.1

### What happened?

Some users are experiencing an issue when attempting to access the Accounts page in our portal. For those affected, the loading indicator, which only spins while account data is being fetched, doesn't stop. This results in an inaccessible Accounts page as the loading indicator continues to spin indefinitely, blocking the user interface.

### Reproduction

1. Start the web application.
2. Sign in
3. Try to navigate to the Accounts page from the top navigation dropdown menu.
4. Observe that the loading indicator activates and doesn't deactivate, leaving the Accounts page inaccessible.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](link-to-code-of-conduct)
- [X] I checked the [current issues](https://github.com/{owner}/{repo}/issues) for duplicate problems

**Comment by volpet2014** [comment]
Resolved in version 2.2.0 of Auth Portal and REST API services..
