### ISSUE TITLE
[Bug]: Registration Email Issues

### ISSUE THREAD

**Issue by anolan23** [vitg-gsa-automation/earlyadopters#4]
### Portal version

2.1.1

### What happened?

Two issues were identified in the registration confirmation email sent to new users:

1. **Email Text Truncation**: The text in the confirmation email is being truncated and not displayed completely. This leads to incomplete information being presented to the user.

2.  **Incorrect CC Value**: The confirmation email was CC'd to the wrong email address. The correct address should be devops@volpegroup.com.

### Reproduction

1. Register a new user through the Public portal.
2. Check the confirmation email sent to the user.
3. Observe the truncated text in the email body.
4. Check the email headers and observe that the CC field contains an incorrect email address instead of devops@volpegroup.com.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](link-to-code-of-conduct)
- [X] I checked the [current issues](https://github.com/{owner}/{repo}/issues) for duplicate problems

**Comment by anolan23** [comment]
I fixed the email truncation and CC value. Will close this issue when 2.2.0 is deployed and tested

**Comment by volpet2014** [comment]
Resolved in version 2.2.0 of Auth Portal.
