### ISSUE TITLE
Test file crashed FedRAMP validator

### ISSUE THREAD

**Issue by gregelin** [vitg-gsa-automation/earlyadopters#5]
### Portal version

Version: 2.1.1 | Last Built: July 27, 2023

### What happened?

Uploaded an XML SSP and portal threw javascript error file not found.

<img width="2168" alt="fedramp-early-adopters-fail" src="https://github.com/vitg-gsa-automation/earlyadopters/assets/24979/813141de-062d-4f0e-8f5a-e2c8eb8a39bd">

### Reproduction

1. Generated an OSCAL SSP in xml
2. Shared file internally via pastebin  (https://pastebin.com/3mqiSvqh)
3. Displayed as raw, saved/downloaded adding .xml to file
4. Logged into Early Adopters Portal and tested
5. Passed Basic and NIST checks
6. Crashed FedRAMP rules with file not found

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](link-to-code-of-conduct)
- [X] I checked the [current issues](https://github.com/{owner}/{repo}/issues) for duplicate problems

**Comment by ThomAPenn** [comment]
@gregelin  The file wasn't created using the  server side bundle.  Thank you for bringing this issue to the4 forefront.  This should be fixed with subsequent releases.    Rev4 and Rev5 have been separated so this should fix the issue.

**Comment by volpet2014** [comment]
@gregelin - A simple work around would be to try and replace the UTF-16 with UTF-8 in the uploaded SSP file to be validated.

**Comment by gregelin** [comment]
@volpet2014 Just tried a file with UTF-8 set. 

<img width="1682" alt="image" src="https://github.com/vitg-gsa-automation/earlyadopters/assets/24979/71e36a55-1d01-4575-a634-841a1048c5bf">

**Comment by gregelin** [comment]
@volpet2014 I switched `utf-16` to `utf-8` as per suggestion and received a different result. Error checking.  See below:

<img width="1674" alt="image" src="https://github.com/vitg-gsa-automation/earlyadopters/assets/24979/3f8d3288-7076-428d-9995-e7ea1bfda220">

**Comment by ThomAPenn** [comment]
Ater running the OSCAL-CLI validations in with the command line tool we get the same output as the validator from the site.  The only way to deal with this is to fix the errors and try again.  Try fixing your time element first and rerun the validator.

**Comment by ThomAPenn** [comment]
[FedRamp-Rev-4-Test-SSP.ERROR.txt](https://github.com/vitg-gsa-automation/earlyadopters/files/12338581/FedRamp-Rev-4-Test-SSP.ERROR.txt)

**Comment by gregelin** [comment]
@ThomAPenn We're not uploading files that are passing many tests. We no longer have the issue related to this ticket. If you have fixed what you needed to fix in release 2.2, I think this issue can be closed unless there is something related to NIST.

**Comment by ThomAPenn** [comment]
Thank you and have a pleasant day.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
