### ISSUE TITLE
[Bug]: "current issues" link produces 404

### ISSUE THREAD

**Issue by gregelin** [vitg-gsa-automation/earlyadopters#6]
### Portal version

n/a

### What happened?

I went to check "current issues" for duplicate problems and linked failed for me (@gregelin) while logged into GitHub.

Also the Code of Conduct link just goes to the issue page.

URL: https://github.com/%7Bowner%7D/%7Brepo%7D/issues
URL: https://github.com/vitg-gsa-automation/earlyadopters/issues/link-to-code-of-conduct

<img width="2168" alt="image" src="https://github.com/vitg-gsa-automation/earlyadopters/assets/24979/ffe2b1ce-0755-4c86-b840-2010750172a1">

<img width="2168" alt="image" src="https://github.com/vitg-gsa-automation/earlyadopters/assets/24979/0ce66d38-c4c8-4619-9e0d-6952b8ca0fee">

### Reproduction

Click the Code of Conduct and current issues link below on this page.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](link-to-code-of-conduct)
- [X] I checked the [current issues](https://github.com/{owner}/{repo}/issues) for duplicate problems

**Comment by anolan23** [comment]
Thank you, I have fixed the links. I will close this now

**Comment by gregelin** [comment]
Thanks!
