### ISSUE TITLE
[Bug]: Minified XML behaves differently than "pretty" printed XML

### ISSUE THREAD

**Issue by bryaneaton** [vitg-gsa-automation/earlyadopters#7]
### Portal version

v2.1.1

### What happened?

i have one XML file, formatted in two ways:

[minified](https://pastebin.com/raw/8MNLNuFk)
[pretty-printed](https://pastebin.com/AKsQU0yN)

The pretty printed XML will pass the first validation, the minified version will fail.  

### Reproduction

Save the two pastebin strings as XML files, run through validator on GSA early adopter site. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vitg-gsa-automation/earlyadopters/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vitg-gsa-automation/earlyadopters/issues) for duplicate problems

**Comment by ThomAPenn** [comment]
Sorry for the inconvenience.  Since there are no whitespaces or any other formatting then it handles it as one long string.  I have code that I am working on that puts the file in a 'pretty' mode.   Thank you for your time and we will address during the next release.

Thanks,
 Thomas Penna

**Comment by volpet2014** [comment]
Addressed and fixed in V2.3 of REST API and portals.
