### ISSUE TITLE
[Bug]: Confusing Schematron Error Message

### ISSUE THREAD

**Issue by gregelin** [vitg-gsa-automation/earlyadopters#8]
### Portal version

FedRAMP Authorization Portal | Version: 2.1.1 | Last Built: July 27, 2023

### What happened?

Receiving an error message: "implementation status is correct"

<img width="1321" alt="Screenshot 2023-08-18 at 12 33 36 PM" src="https://github.com/vitg-gsa-automation/earlyadopters/assets/24979/4a48c476-ede5-4a35-b61c-bd5c302249ed">

<img width="1303" alt="Screenshot 2023-08-18 at 12 35 49 PM" src="https://github.com/vitg-gsa-automation/earlyadopters/assets/24979/eaf6baf6-a9f1-41a6-ab1e-9892cfcd5fe4">

### Reproduction

Generated an SSP with control implementations containing where `implemented-requirement` element has `prop` that with name `implementation status` that also contains an UUID and what we think is a proper `value` for status and we are given an error saying are status is correct. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vitg-gsa-automation/earlyadopters/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vitg-gsa-automation/earlyadopters/issues) for duplicate problems

**Comment by ThomAPenn** [comment]
Thank you for bringing this to the light Greg.  We will do the research and see what might have caused the incorrect error posting.

**Comment by gregelin** [comment]
@ThomAPenn No problem. Site is running smoothly and I like the error detailed view displaying highlighted section. Nice job!

**Comment by ThomAPenn** [comment]
@gregelin I see this was for version 2.1.1...  Sorry about the confusion.

**Comment by gregelin** [comment]
@ThomAPenn I just copied the version information from the site that is currently running.

**Comment by ThomAPenn** [comment]
Can I have a copy of the .XML file in which I can test? Send it to my email account or ***@***.***  This way I can run the same test.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by volpet2014** [comment]
Taking a look that the xml viewer it looks like you have implementation status set as "fully implemented"  the correct FedRAMP value is "implemented".  This could be causing the error.

**Comment by volpet2014** [comment]
The output error should state that the implementation status is "incorrect".  Adding Dimitri to ticket for awareness and correction.

**Comment by volpet2014** [comment]
A list of the FedRAMP acceptable implementation statuses can be found in the fedramp-values.xml file under the fedramp-automation repo under the resources folder:  https://github.com/GSA/fedramp-automation/tree/master/dist/content/rev4/resources/xml

**Comment by gregelin** [comment]
@volpet2014 @ThomAPenn -- OK. We will read that text as typo that should read ""implementation status is incorrect." Thanks.

**Comment by anolan23** [comment]
I think the message "Implementation status is correct" is what the assertion is and what it is checking for.

It's checking that the "Implementation status is correct" and as a result shows "Error" because it is not correct. I may be able to show more info from the SVRL

**Comment by gregelin** [comment]
Yeah, I’m beginning to understand that Schematron sometimes expresses what the rule is, e.g. “implementation status is correct” and we get an error that a document is failing that rule.

Maybe the rule should read something like, “…implementation status must be a valid FedRAMP enumerated value”

Greg Elin
Principal OSCAL Engineer
***@***.*** | m: 917-304-3488


From: anolan23 ***@***.***>
Date: Sunday, August 20, 2023 at 11:50 AM
To: vitg-gsa-automation/earlyadopters ***@***.***>
Cc: Greg Elin ***@***.***>, Mention ***@***.***>
Subject: Re: [vitg-gsa-automation/earlyadopters] [Bug]: (Issue #8)

I think the message "Implementation status is correct" is what the assertion is and what it is checking for.

It's checking that the "Implementation status is correct" and as a result shows "Error" because it is not correct. I may be able to show more info from the SVRL

**Comment by volpet2014** [comment]
Modifying the error message to be more meaning full and not make it an error in next release of REST API validation services.
