### ISSUE TITLE
[Bug]: Invalid XML File Passing Through "/Check" Method Without Validation Errors

### ISSUE THREAD

**Issue by anolan23** [vitg-gsa-automation/earlyadopters#9]
### Portal version

v2.2.0

### What happened?

An [Invalid XML file](https://pastebin.com/eLHWf5Dt) **(line 24)** is being processed without validation errors by the `/Check` method, leading to a `java.io.FileNotFoundException` later in the validation process. The `/Check` method is expected to validate the XML and report any issues, but it's not catching the faulty comment.

![Screenshot 2023-08-21 102013](https://github.com/vitg-gsa-automation/earlyadopters/assets/57581908/896654a7-5250-4fe0-805c-746ccef6cebb)

### Reproduction

1. Navigate to the Validations page in the portal.
2. Select the [Invalid XML file](https://pastebin.com/eLHWf5Dt) containing a malformed comment (e.g., "!-- Additional revision assemblies as needed. --").
3. Trigger the validation process, which makes a call to the integration service's `/Check` method.
4. Observe that the `/Check` method does not report any validation errors.
5. View the the `java.io.FileNotFoundException` in the UI later in the validation process.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vitg-gsa-automation/earlyadopters/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vitg-gsa-automation/earlyadopters/issues) for duplicate problems

**Comment by volpet2014** [comment]
Resolved with minor patch to integration services in version 2.2.0
